spring:
  ###### 数据源配置【开始】 ######
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/starry?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      connection-timeout: 30000 #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
#      idle-timeout: 600000 #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
#      max-lifetime: 1800000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上，参考MySQL wait_timeout参数（show variables like '%timeout%';）
#      maximum-pool-size: 9 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  ###### 数据源配置【结束】 ######

  ###### JPA配置【开始】 ######
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update # create、create-drop、update、validate、none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect  # 方言设置，或者MySQL5InnoDBDialect
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.129.131:9300
      cluster-name: docker-cluster #默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口。
mybatis:
  type-aliases-package: com.starry.domain.entity
  mapper-locations: classpath:com.starry.domain.mapper/*.xml
server:
  port: 8008
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  trackerList[0]: "192.168.129.131:22122"
  webServerUrl: "192.168.129.131/"
fdfsthumbimage:
  width: 200
  height: 200
fdfspool:
    #从池中借出的对象的最大数目
    maxTotal: 153
    #获取连接时的最大等待毫秒数100
    maxWaitMillis: 102